In [1]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("unimelb_training.csv",low_memory=False)
data.head()

,Grant.Application.ID,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,Start.date,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,...,Faculty.No..15,With.PHD.15,No..of.Years.in.Uni.at.Time.of.Grant.15,Number.of.Successful.Grant.15,Number.of.Unsuccessful.Grant.15,A..15,A.15,B.15,C.15,Unnamed: 251
0,1,1,NaN,NaN,A,8/11/05,280199.0,100.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,2B,10A,B,11/11/05,280103.0,30.0,280106.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,29A,10B,A,14/11/05,321004.0,60.0,321216.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,40D,10B,C,15/11/05,270602.0,50.0,320602.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0,59C,10A,A,16/11/05,260500.0,34.0,280000.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
list(data)

['Grant.Application.ID',
 'Grant.Status',
 'Sponsor.Code',
 'Grant.Category.Code',
 'Contract.Value.Band...see.note.A',
 'Start.date',
 'RFCD.Code.1',
 'RFCD.Percentage.1',
 'RFCD.Code.2',
 'RFCD.Percentage.2',
 'RFCD.Code.3',
 'RFCD.Percentage.3',
 'RFCD.Code.4',
 'RFCD.Percentage.4',
 'RFCD.Code.5',
 'RFCD.Percentage.5',
 'SEO.Code.1',
 'SEO.Percentage.1',
 'SEO.Code.2',
 'SEO.Percentage.2',
 'SEO.Code.3',
 'SEO.Percentage.3',
 'SEO.Code.4',
 'SEO.Percentage.4',
 'SEO.Code.5',
 'SEO.Percentage.5',
 'Person.ID.1',
 'Role.1',
 'Year.of.Birth.1',
 'Country.of.Birth.1',
 'Home.Language.1',
 'Dept.No..1',
 'Faculty.No..1',
 'With.PHD.1',
 'No..of.Years.in.Uni.at.Time.of.Grant.1',
 'Number.of.Successful.Grant.1',
 'Number.of.Unsuccessful.Grant.1',
 'A..1',
 'A.1',
 'B.1',
 'C.1',
 'Person.ID.2',
 'Role.2',
 'Year.of.Birth.2',
 'Country.of.Birth.2',
 'Home.Language.2',
 'Dept.No..2',
 'Faculty.No..2',
 'With.PHD.2',
 'No..of.Years.in.Uni.at.Time.of.Grant.2',
 'Number.of.Successful.Grant.2',
 'Number.of.Unsuccessful.Grant.2',
 'A..2',
 'A.2',
 'B.2',
 'C.2',
 'Person.ID.3',
 'Role.3',
 'Year.of.Birth.3',
 'Country.of.Birth.3',
 'Home.Language.3',
 'Dept.No..3',
 'Faculty.No..3',
 'With.PHD.3',
 'No..of.Years.in.Uni.at.Time.of.Grant.3',
 'Number.of.Successful.Grant.3',
 'Number.of.Unsuccessful.Grant.3',
 'A..3',
 'A.3',
 'B.3',
 'C.3',
 'Person.ID.4',
 'Role.4',
 'Year.of.Birth.4',
 'Country.of.Birth.4',
 'Home.Language.4',
 'Dept.No..4',
 'Faculty.No..4',
 'With.PHD.4',
 'No..of.Years.in.Uni.at.Time.of.Grant.4',
 'Number.of.Successful.Grant.4',
 'Number.of.Unsuccessful.Grant.4',
 'A..4',
 'A.4',
 'B.4',
 'C.4',
 'Person.ID.5',
 'Role.5',
 'Year.of.Birth.5',
 'Country.of.Birth.5',
 'Home.Language.5',
 'Dept.No..5',
 'Faculty.No..5',
 'With.PHD.5',
 'No..of.Years.in.Uni.at.Time.of.Grant.5',
 'Number.of.Successful.Grant.5',
 'Number.of.Unsuccessful.Grant.5',
 'A..5',
 'A.5',
 'B.5',
 'C.5',
 'Person.ID.6',
 'Role.6',
 'Year.of.Birth.6',
 'Country.of.Birth.6',
 'Home.Language.6',
 'Dept.No..6',
 'Faculty.No..6',
 'With.PHD.6',
 'No..of.Years.in.Uni.at.Time.of.Grant.6',
 'Number.of.Successful.Grant.6',
 'Number.of.Unsuccessful.Grant.6',
 'A..6',
 'A.6',
 'B.6',
 'C.6',
 'Person.ID.7',
 'Role.7',
 'Year.of.Birth.7',
 'Country.of.Birth.7',
 'Home.Language.7',
 'Dept.No..7',
 'Faculty.No..7',
 'With.PHD.7',
 'No..of.Years.in.Uni.at.Time.of.Grant.7',
 'Number.of.Successful.Grant.7',
 'Number.of.Unsuccessful.Grant.7',
 'A..7',
 'A.7',
 'B.7',
 'C.7',
 'Person.ID.8',
 'Role.8',
 'Year.of.Birth.8',
 'Country.of.Birth.8',
 'Home.Language.8',
 'Dept.No..8',
 'Faculty.No..8',
 'With.PHD.8',
 'No..of.Years.in.Uni.at.Time.of.Grant.8',
 'Number.of.Successful.Grant.8',
 'Number.of.Unsuccessful.Grant.8',
 'A..8',
 'A.8',
 'B.8',
 'C.8',
 'Person.ID.9',
 'Role.9',
 'Year.of.Birth.9',
 'Country.of.Birth.9',
 'Home.Language.9',
 'Dept.No..9',
 'Faculty.No..9',
 'With.PHD.9',
 'No..of.Years.in.Uni.at.Time.of.Grant.9',
 'Number.of.Successful.Grant.9',
 'Number.of.Unsuccessful.Grant.9',
 'A..9',
 'A.9',
 'B.9',
 'C.9',
 'Person.ID.10',
 'Role.10',
 'Year.of.Birth.10',
 'Country.of.Birth.10',
 'Home.Language.10',
 'Dept.No..10',
 'Faculty.No..10',
 'With.PHD.10',
 'No..of.Years.in.Uni.at.Time.of.Grant.10',
 'Number.of.Successful.Grant.10',
 'Number.of.Unsuccessful.Grant.10',
 'A..10',
 'A.10',
 'B.10',
 'C.10',
 'Person.ID.11',
 'Role.11',
 'Year.of.Birth.11',
 'Country.of.Birth.11',
 'Home.Language.11',
 'Dept.No..11',
 'Faculty.No..11',
 'With.PHD.11',
 'No..of.Years.in.Uni.at.Time.of.Grant.11',
 'Number.of.Successful.Grant.11',
 'Number.of.Unsuccessful.Grant.11',
 'A..11',
 'A.11',
 'B.11',
 'C.11',
 'Person.ID.12',
 'Role.12',
 'Year.of.Birth.12',
 'Country.of.Birth.12',
 'Home.Language.12',
 'Dept.No..12',
 'Faculty.No..12',
 'With.PHD.12',
 'No..of.Years.in.Uni.at.Time.of.Grant.12',
 'Number.of.Successful.Grant.12',
 'Number.of.Unsuccessful.Grant.12',
 'A..12',
 'A.12',
 'B.12',
 'C.12',
 'Person.ID.13',
 'Role.13',
 'Year.of.Birth.13',
 'Country.of.Birth.13',
 'Home.Language.13',
 'Dept.No..13',
 'Faculty.No..13',
 'With.PHD.13',
 'No..of.Years.in.Uni.at.Time.of.Grant.13',
 'Number.of.Successful.Grant.13',
 'Number.of.Unsuccessful.Grant.13',
 'A..13',
 'A.13',
 'B.13',
 'C.13',
 'Person.ID.14',
 'Role.14',
 'Year.of.Birth.14',
 'Country.of.Birth.14',
 'Home.Language.14',
 'Dept.No..14',
 'Faculty.No..14',
 'With.PHD.14',
 'No..of.Years.in.Uni.at.Time.of.Grant.14',
 'Number.of.Successful.Grant.14',
 'Number.of.Unsuccessful.Grant.14',
 'A..14',
 'A.14',
 'B.14',
 'C.14',
 'Person.ID.15',
 'Role.15',
 'Year.of.Birth.15',
 'Country.of.Birth.15',
 'Home.Language.15',
 'Dept.No..15',
 'Faculty.No..15',
 'With.PHD.15',
 'No..of.Years.in.Uni.at.Time.of.Grant.15',
 'Number.of.Successful.Grant.15',
 'Number.of.Unsuccessful.Grant.15',
 'A..15',
 'A.15',
 'B.15',
 'C.15',
 'Unnamed: 251']

In [6]:
data.isna().sum()

Grant.Application.ID                   0
Grant.Status                           0
Sponsor.Code                         912
Grant.Category.Code                  912
Contract.Value.Band...see.note.A    3563
                                    ...
A..15                               8706
A.15                                8706
B.15                                8706
C.15                                8708
Unnamed: 251                        8708
Length: 252, dtype: int64

In [7]:
data1=data.iloc[:,1:40]
data1

,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,Start.date,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,RFCD.Code.3,...,Home.Language.1,Dept.No..1,Faculty.No..1,With.PHD.1,No..of.Years.in.Uni.at.Time.of.Grant.1,Number.of.Successful.Grant.1,Number.of.Unsuccessful.Grant.1,A..1,A.1,B.1
0,1,NaN,NaN,A,8/11/05,280199.0,100.0,0.0,0.0,0.0,...,Other,3073.0,31.0,NaN,Less than 0,0.0,0.0,4.0,2.0,0.0
1,1,2B,10A,B,11/11/05,280103.0,30.0,280106.0,30.0,280203.0,...,NaN,2538.0,25.0,Yes,more than 15,0.0,0.0,6.0,12.0,2.0
2,1,29A,10B,A,14/11/05,321004.0,60.0,321216.0,40.0,0.0,...,NaN,2923.0,25.0,Yes,>5 to 10,0.0,0.0,0.0,3.0,5.0
3,1,40D,10B,C,15/11/05,270602.0,50.0,320602.0,50.0,0.0,...,NaN,2678.0,25.0,Yes,>5 to 10,0.0,0.0,0.0,3.0,13.0
4,0,59C,10A,A,16/11/05,260500.0,34.0,280000.0,33.0,290000.0,...,NaN,2153.0,19.0,Yes,>5 to 10,0.0,0.0,3.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8703,1,21A,50A,A,23/12/08,321028.0,100.0,0.0,0.0,0.0,...,NaN,2763.0,25.0,Yes,>5 to 10,1.0,11.0,4.0,7.0,2.0
8704,1,21A,50A,A,23/12/08,340299.0,50.0,390114.0,50.0,0.0,...,NaN,1678.0,13.0,Yes,>5 to 10,2.0,0.0,0.0,5.0,15.0
8705,0,137A,30B,NaN,24/12/08,NaN,NaN,NaN,NaN,NaN,...,NaN,2103.0,19.0,Yes,more than 15,1.0,3.0,3.0,4.0,5.0
8706,1,21A,50A,A,24/12/08,280210.0,40.0,239901.0,40.0,280206.0,...,NaN,2153.0,19.0,Yes,>10 to 15,2.0,1.0,0.0,3.0,7.0
8707,1,21A,50A,A,24/12/08,321012.0,70.0,321005.0,30.0,0.0,...,NaN,2678.0,25.0,Yes,>10 to 15,9.0,26.0,0.0,13.0,12.0

In [8]:
data1.isna().sum()

Grant.Status                                 0
Sponsor.Code                               912
Grant.Category.Code                        912
Contract.Value.Band...see.note.A          3563
Start.date                                   0
RFCD.Code.1                                634
RFCD.Percentage.1                          634
RFCD.Code.2                                634
RFCD.Percentage.2                          634
RFCD.Code.3                                634
RFCD.Percentage.3                          634
RFCD.Code.4                                634
RFCD.Percentage.4                          634
RFCD.Code.5                                634
RFCD.Percentage.5                          634
SEO.Code.1                                 664
SEO.Percentage.1                           664
SEO.Code.2                                 664
SEO.Percentage.2                           664
SEO.Code.3                                 664
SEO.Percentage.3                           664
SEO.Code.4                                 664
SEO.Percentage.4                           664
SEO.Code.5                                 664
SEO.Percentage.5                           664
Person.ID.1                                523
Role.1                                      98
Year.of.Birth.1                            527
Country.of.Birth.1                        1280
Home.Language.1                           7910
Dept.No..1                                 870
Faculty.No..1                              873
With.PHD.1                                3595
No..of.Years.in.Uni.at.Time.of.Grant.1    1481
Number.of.Successful.Grant.1               523
Number.of.Unsuccessful.Grant.1             523
A..1                                       523
A.1                                        523
B.1                                        523
dtype: int64

In [9]:
data2= data1.drop(['Country.of.Birth.1','Sponsor.Code','Grant.Category.Code','Start.date','Contract.Value.Band...see.note.A','Home.Language.1','With.PHD.1','No..of.Years.in.Uni.at.Time.of.Grant.1'],axis =1)

In [10]:
data2.shape

(8708, 31)

In [11]:
data2.isna().sum()

Grant.Status                        0
RFCD.Code.1                       634
RFCD.Percentage.1                 634
RFCD.Code.2                       634
RFCD.Percentage.2                 634
RFCD.Code.3                       634
RFCD.Percentage.3                 634
RFCD.Code.4                       634
RFCD.Percentage.4                 634
RFCD.Code.5                       634
RFCD.Percentage.5                 634
SEO.Code.1                        664
SEO.Percentage.1                  664
SEO.Code.2                        664
SEO.Percentage.2                  664
SEO.Code.3                        664
SEO.Percentage.3                  664
SEO.Code.4                        664
SEO.Percentage.4                  664
SEO.Code.5                        664
SEO.Percentage.5                  664
Person.ID.1                       523
Role.1                             98
Year.of.Birth.1                   527
Dept.No..1                        870
Faculty.No..1                     873
Number.of.Successful.Grant.1      523
Number.of.Unsuccessful.Grant.1    523
A..1                              523
A.1                               523
B.1                               523
dtype: int64